server.port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  application.name: check-service

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  bootstrap:
    address: localhost:9091

  update:
    topic: inquiry-input

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

geoip:
  uri: https://freegeoip.app/json/

updateservice:
  uri: http://localhost:8081/updates

logging.level.org.springframework.cloud.contract: debug